'use client'

import { AnimatePresence, motion } from 'framer-motion'
import type { Task } from '@/lib/observability/types'

interface TaskInspectorProps { task: Task | null; onClose: () => void; onReprocess?: (id: string) => Promise<void> }
const format = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : '—'

export function TaskInspector({ task, onClose, onReprocess }: TaskInspectorProps) {
  return <AnimatePresence>{task ? <motion.div className="fixed inset-0 z-50 flex items-end justify-center p-4 sm:items-center" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <button type="button" aria-label="Close inspector" onClick={onClose} className="absolute inset-0 bg-black/70" style={{ backdropFilter: 'blur(24px)' }} />
    <motion.div role="dialog" aria-modal="true" className="relative z-10 w-full max-w-3xl overflow-hidden rounded-3xl border border-white/10 bg-[#0b0b11]/95 shadow-[0_40px_120px_-30px_rgba(0,0,0,0.95)]" initial={{ y: 40, scale: .97 }} animate={{ y: 0, scale: 1 }}>
      <div className="flex items-start justify-between border-b border-white/10 p-6"><div><h2 className="text-lg font-semibold">Inspector: <span className="font-mono text-cyan-300">{task.id}</span></h2><div className="mt-2 font-mono text-xs uppercase tracking-widest text-neutral-400">{task.status} · attempt {task.attempts}/{task.max_attempts}</div></div><div className="flex gap-2"><button type="button" onClick={() => onReprocess?.(task.id)} disabled={task.status !== 'dlq'} className="rounded-full border border-rose-400/30 px-3 py-1.5 font-mono text-xs text-rose-300 disabled:opacity-30">Reprocess DLQ</button><button type="button" onClick={onClose} className="rounded-full border border-white/10 px-3 py-1.5 font-mono text-xs text-neutral-300">Esc</button></div></div>
      <div className="grid gap-5 p-6 sm:grid-cols-2"><div><h3 className="font-mono text-xs uppercase tracking-widest text-neutral-500">Payload</h3><pre className="glass-scroll mt-2 max-h-56 overflow-auto rounded-2xl border border-white/5 bg-black/50 p-4 font-mono text-xs text-cyan-200/90">{JSON.stringify(task.payload, null, 2)}</pre><div className="mt-3 space-y-1 font-mono text-xs text-neutral-500"><p>created {format(task.created_at)}</p><p>scheduled {format(task.scheduled_for)}</p><p>lease {format(task.lease_expires_at)}</p><p>error <span className="text-rose-300">{task.last_error || '—'}</span></p></div></div><div><h3 className="font-mono text-xs uppercase tracking-widest text-neutral-500">Execution history</h3><div className="glass-scroll mt-2 max-h-72 space-y-2 overflow-auto rounded-2xl border border-white/5 bg-black/40 p-4 font-mono text-xs">{task.executions?.length ? task.executions.map((execution) => <div key={execution.id} className="border-b border-white/5 pb-2 last:border-0"><div className="flex justify-between"><span className="text-neutral-300">attempt {execution.attempt_number}</span><span className={execution.status === 'succeeded' ? 'text-emerald-300' : execution.status === 'abandoned' || execution.status === 'failed' ? 'text-rose-300' : 'text-cyan-300'}>{execution.status}</span></div><div className="mt-1 text-neutral-500">worker {execution.worker_id?.slice(0, 8) || '—'} · {format(execution.started_at)}</div>{execution.error ? <div className="mt-1 text-rose-300">{execution.error}</div> : null}</div>) : <span className="text-neutral-600">No execution attempts yet.</span>}</div></div></div>
    </motion.div>
  </motion.div> : null}</AnimatePresence>
}
